'use strict'

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const REQUEST_USER_DATA = 'REQUEST_USER_DATA'
export const REQUEST_USER_DATA_SUCCESS = 'REQUEST_USER_DATA_SUCCESS'
export const REQUEST_USER_DATA_FAILURE = 'REQUEST_USER_DATA_FAILURE'